
language: c
sudo: false

before_install:
	- curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
	- chmod 755 pkg-build.sh
	- ./pkg-build.sh bootstrap

install:
	- ./pkg-build.sh install_github sahilseth/packagedocs
	- ./pkg-build.sh install_deps

script:
	- ./pkg-build.sh run_build
	- ./pkg-build.sh run_check

after_failure:
	- ./pkg-build.sh dump_logs

notifications:
	email:
	on_success: change
	on_failure: change

env:
	matrix:
	- RVERSION=oldrel
	- RVERSION=release
	- RVERSION=devel
	- RVERSION=3.1.3
	- RVERSION=3.1.0
